# Generated by Django 4.1.3 on 2022-12-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
