# Generated by Django 4.1.3 on 2022-12-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patient_address_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
