# Generated by Django 4.1.3 on 2022-12-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='descrption',
            field=models.TextField(blank=True, default='None', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6, null=True),
        ),
    ]
