# Generated by Django 4.1.3 on 2022-12-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_descrption_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='descrption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
