# Generated by Django 4.1.3 on 2022-12-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patient_descrption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='descrption',
            field=models.TextField(blank=True, default='None', max_length=500, null=True),
        ),
    ]
