# Generated by Django 4.1 on 2022-12-15 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_specialization_doctor_email_doctor_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='docter_schedule',
            fields=[
                ('Date_Book', models.DateField(primary_key=True, serialize=False)),
                ('data_8to10', models.BooleanField(default=False)),
                ('data_10to12', models.BooleanField(default=False)),
                ('data_12to1', models.BooleanField(default=False)),
                ('data_1to2', models.BooleanField(default=False)),
                ('data_2to4', models.BooleanField(default=False)),
                ('data_4to6', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
