# Generated by Django 4.1 on 2022-12-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_docter_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, default='Doctor', max_length=100, null=True),
        ),
    ]
