# Generated by Django 4.1.3 on 2022-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_docter_schedule_doctor_alter_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, choices=[('Diagnostic_radiology', 'Diagnostic_radiology'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Blood', 'Blood')], max_length=100, null=True),
        ),
    ]
