# Generated by Django 4.1 on 2022-12-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_descrption_alter_patient_gender'),
        ('doctor', '0008_alter_specialization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_10to12',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_12to1',
            new_name='data2',
        ),
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_1to2',
            new_name='data3',
        ),
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_2to4',
            new_name='data4',
        ),
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_4to6',
            new_name='data5',
        ),
        migrations.RenameField(
            model_name='docter_schedule',
            old_name='data_8to10',
            new_name='data6',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('data_time', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
