# Generated by Django 4.1 on 2022-12-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, choices=[('Diagnostic_radiology', 'Diagnostic_radiology'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Blood', 'Blood')], max_length=100, null=True),
        ),
    ]
