# Generated by Django 4.1.3 on 2022-12-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_specialization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='descrption',
            field=models.TextField(blank=True, default='None', max_length=500, null=True),
        ),
    ]
