# Generated by Django 4.1.3 on 2022-12-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_manger_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
